<template>
  <p>
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      HOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOMEHOME HOME
      
 </p>
</template>

<script>
    export default {
        name: 'Home',
        components: {
            
        },
        data() {
            return {
            }
        }
    }
</script>